groups: []
resources: []
resource_types: []
jobs:
- name: hello-world
  plan:
  - task: hello world
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: alpine
      run:
        path: sh
        args:
        - -c
        - echo 'hello world'
