groups: []
resources: []
resource_types: []
jobs:
- name: hello-world
  plan:
  - task: hello world
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: alpine
      run:
        path: sh
        args:
        - -c
        - "\t\t\t\t\t\t\t echo \"this is a test\"\n\t\t\t\t\t\t\t echo \"i'm going
          to do a curl\"\n\t\t\t\t\t\t\t curl 'https://api.ipify.org?format=json'\n\t\t\t\t\t\t "
